version: "3.9"

services:

  app:
    build: .
    container_name: rag-app
    command: python main.py
    volumes:
      - .:/app
    working_dir: /app

  lint:
    build: .
    container_name: rag-lint
    command: ruff check . --fix
    volumes:
      - .:/app
    working_dir: /app

  lint-check:
    build: .
    container_name: rag-lint-check
    command: ruff check .
    volumes:
      - .:/app
    working_dir: /app

  format-check:
    build: .
    container_name: rag-format-check
    command: black --check .
    volumes:
      - .:/app
    working_dir: /app

  format:
    build: .
    container_name: rag-format
    command: black .
    volumes:
      - .:/app
    working_dir: /app
    
  test:
    build: .
    command: pytest -q
    volumes:
      - .:/app
    working_dir: /app

  evaluate_embeddings:
    build: .
    command: python run_evaluation.py
    volumes:
      - .:/app
    working_dir: /app